// Course Constants
export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST'
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS'
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL'
export const COURSE_CREATE_RESET = 'COURSE_CREATE_RESET'

export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'

export const COURSE_VIEW_REQUEST = 'COURSE_VIEW_REQUEST'
export const COURSE_VIEW_SUCCESS = 'COURSE_VIEW_SUCCESS'
export const COURSE_VIEW_FAIL = 'COURSE_VIEW_FAIL'

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST'
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS'
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL'
export const COURSE_UPDATE_RESET = 'COURSE_UPDATE_RESET'

export const PUBLISH_COURSE_REQUEST = 'PUBLISH_COURSE_REQUEST'
export const PUBLISH_COURSE_SUCCESS = 'PUBLISH_COURSE_SUCCESS'
export const PUBLISH_COURSE_FAIL = 'PUBLISH_COURSE_FAIL'
export const PUBLISH_COURSE_RESET = 'PUBLISH_COURSE_RESET'

export const UNPUBLISH_COURSE_REQUEST = 'UNPUBLISH_COURSE_REQUEST'
export const UNPUBLISH_COURSE_SUCCESS = 'UNPUBLISH_COURSE_SUCCESS'
export const UNPUBLISH_COURSE_FAIL = 'UNPUBLISH_COURSE_FAIL'
export const UNPUBLISH_COURSE_RESET = 'UNPUBLISH_COURSE_RESET'


// Lesson Constants
export const LESSON_CREATE_REQUEST = 'LESSON_CREATE_REQUEST'
export const LESSON_CREATE_SUCCESS = 'LESSON_CREATE_SUCCESS'
export const LESSON_CREATE_FAIL = 'LESSON_CREATE_FAIL'
export const LESSON_CREATE_RESET = 'LESSON_CREATE_RESET'

export const LESSON_UPDATE_REQUEST = 'LESSON_UPDATE_REQUEST'
export const LESSON_UPDATE_SUCCESS = 'LESSON_UPDATE_SUCCESS'
export const LESSON_UPDATE_FAIL = 'LESSON_UPDATE_FAIL'
export const LESSON_UPDATE_RESET = 'LESSON_UPDATE_RESET'
