export const LIST_INSTRUCTORS_REQUEST = 'LIST_INSTRUCTORS_REQUEST'
export const LIST_INSTRUCTORS_SUCCESS = 'LIST_INSTRUCTORS_SUCCESS'
export const LIST_INSTRUCTORS_FAIL = 'LIST_INSTRUCTORS_FAIL'

export const LIST_STUDENTS_REQUEST = 'LIST_STUDENTS_REQUEST'
export const LIST_STUDENTS_SUCCESS = 'LIST_STUDENTS_SUCCESS'
export const LIST_STUDENTS_FAIL = 'LIST_STUDENTS_FAIL'