// Manage Instructors Constants 

export const LIST_INSTRUCTORS_REQUEST = 'LIST_INSTRUCTORS_REQUEST'
export const LIST_INSTRUCTORS_SUCCESS = 'LIST_INSTRUCTORS_SUCCESS'
export const LIST_INSTRUCTORS_FAIL = 'LIST_INSTRUCTORS_FAIL'

export const BLOCK_INSTRUCTORS_REQUEST = 'BLOCK_INSTRUCTORS_REQUEST'
export const BLOCK_INSTRUCTORS_SUCCESS = 'BLOCK_INSTRUCTORS_SUCCESS'
export const BLOCK_INSTRUCTORS_FAIL = 'BLOCK_INSTRUCTORS_FAIL'

export const UNBLOCK_INSTRUCTORS_REQUEST = 'UNBLOCK_INSTRUCTORS_REQUEST'
export const UNBLOCK_INSTRUCTORS_SUCCESS = 'UNBLOCK_INSTRUCTORS_SUCCESS'
export const UNBLOCK_INSTRUCTORS_FAIL = 'UNBLOCK_INSTRUCTORS_FAIL'


// Manage Students Constants

export const LIST_STUDENTS_REQUEST = 'LIST_STUDENTS_REQUEST'
export const LIST_STUDENTS_SUCCESS = 'LIST_STUDENTS_SUCCESS'
export const LIST_STUDENTS_FAIL = 'LIST_STUDENTS_FAIL'

export const BLOCK_STUDENTS_REQUEST = 'BLOCK_STUDENTS_REQUEST'
export const BLOCK_STUDENTS_SUCCESS = 'BLOCK_STUDENTS_SUCCESS'
export const BLOCK_STUDENTS_FAIL = 'BLOCK_STUDENTS_FAIL'

export const UNBLOCK_STUDENTS_REQUEST = 'UNBLOCK_STUDENTS_REQUEST'
export const UNBLOCK_STUDENTS_SUCCESS = 'UNBLOCK_STUDENTS_SUCCESS'
export const UNBLOCK_STUDENTS_FAIL = 'UNBLOCK_STUDENTS_FAIL'