export const STUDENTS_COURSE_LIST_REQUEST = 'STUDENTS_COURSE_LIST_REQUEST'
export const STUDENTS_COURSE_LIST_SUCCESS = 'STUDENTS_COURSE_LIST_SUCCESS'
export const STUDENTS_COURSE_LIST_FAIL = 'STUDENTS_COURSE_LIST_FAIL'

export const STUDENTS_COURSE_DETAILS_REQUEST = 'STUDENTS_COURSE_DETAILS_REQUEST'
export const STUDENTS_COURSE_DETAILS_SUCCESS = 'STUDENTS_COURSE_DETAILS_SUCCESS'
export const STUDENTS_COURSE_DETAILS_FAIL = 'STUDENTS_COURSE_DETAILS_FAIL'

export const STUDENTS_COURSE_ADDTOCART_REQUEST = 'STUDENTS_COURSE_ADDTOCART_REQUEST'
export const STUDENTS_COURSE_ADDTOCART_SUCCESS = 'STUDENTS_COURSE_ADDTOCART_SUCCESS'
export const STUDENTS_COURSE_ADDTOCART_FAIL = 'STUDENTS_COURSE_ADDTOCART_FAIL'