export const STUDENTS_COURSE_LIST_REQUEST = 'STUDENTS_COURSE_LIST_REQUEST'
export const STUDENTS_COURSE_LIST_SUCCESS = 'STUDENTS_COURSE_LIST_SUCCESS'
export const STUDENTS_COURSE_LIST_FAIL = 'STUDENTS_COURSE_LIST_FAIL'

export const STUDENTS_COURSE_DETAILS_REQUEST = 'STUDENTS_COURSE_DETAILS_REQUEST'
export const STUDENTS_COURSE_DETAILS_SUCCESS = 'STUDENTS_COURSE_DETAILS_SUCCESS'
export const STUDENTS_COURSE_DETAILS_FAIL = 'STUDENTS_COURSE_DETAILS_FAIL'

export const STUDENTS_COURSE_ADDTOCART_REQUEST = 'STUDENTS_COURSE_ADDTOCART_REQUEST'
export const STUDENTS_COURSE_ADDTOCART_SUCCESS = 'STUDENTS_COURSE_ADDTOCART_SUCCESS'
export const STUDENTS_COURSE_ADDTOCART_FAIL = 'STUDENTS_COURSE_ADDTOCART_FAIL'

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST'
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS'
export const CART_LIST_FAIL = 'CART_LIST_FAIL'

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST'
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS'
export const REMOVE_CART_ITEM_FAIL = 'REMOVE_CART_ITEM_FAIL'

export const FREE_ENROLLMENT_COURSE_REQUEST = 'FREE_ENROLLMENT_COURSE_REQUEST'
export const FREE_ENROLLMENT_COURSE_SUCCESS = 'FREE_ENROLLMENT_COURSE_SUCCESS'
export const FREE_ENROLLMENT_COURSE_FAIL = 'FREE_ENROLLMENT_COURSE_FAIL'
export const FREE_ENROLLMENT_COURSE_RESET = 'FREE_ENROLLMENT_COURSE_RESET'

export const LIST_MYCOURSES_REQUEST = 'LIST_MYCOURSES_REQUEST'
export const LIST_MYCOURSES_SUCCESS = 'LIST_MYCOURSES_SUCCESS'
export const LIST_MYCOURSES_FAIL = 'LIST_MYCOURSES_FAIL'

export const MYCOURSES_DETAILS_REQUEST = 'MYCOURSES_DETAILS_REQUEST'
export const MYCOURSES_DETAILS_SUCCESS = 'MYCOURSES_DETAILS_SUCCESS'
export const MYCOURSES_DETAILS_FAIL = 'MYCOURSES_DETAILS_FAIL'

export const MYCOURSE_START_REQUEST = 'MYCOURSE_START_REQUEST'
export const MYCOURSE_START_SUCCESS = 'MYCOURSE_START_SUCCESS'
export const MYCOURSE_START_FAIL = 'MYCOURSE_START_FAIL'

export const MARK_lESSON_COMPLETE_REQUEST = 'MARK_lESSON_COMPLETE_REQUEST'
export const MARK_lESSON_COMPLETE_SUCCESS = 'MARK_lESSON_COMPLETE_SUCCESS'
export const MARK_lESSON_COMPLETE_FAIL = 'MARK_lESSON_COMPLETE_FAIL'

export const LIST_COMPLETE_REQUEST = 'LIST_COMPLETE_REQUEST'
export const LIST_COMPLETE_SUCCESS = 'LIST_COMPLETE_SUCCESS'
export const LIST_COMPLETE_FAIL = 'LIST_COMPLETE_FAIL'

export const PROVIDE_CERTIFICATE_REQUEST = 'PROVIDE_CERTIFICATE_REQUEST'
export const PROVIDE_CERTIFICATE_SUCCESS = 'PROVIDE_CERTIFICATE_SUCCESS'
export const PROVIDE_CERTIFICATE_FAIL = 'PROVIDE_CERTIFICATE_FAIL'
export const PROVIDE_CERTIFICATE_RESET = 'PROVIDE_CERTIFICATE_RESET'

export const COURSE_CREATE_REVIEW_REQUEST = 'COURSE_CREATE_REVIEW_REQUEST'
export const COURSE_CREATE_REVIEW_SUCCESS = 'COURSE_CREATE_REVIEW_SUCCESS'
export const COURSE_CREATE_REVIEW_FAIL = 'COURSE_CREATE_REVIEW_FAIL'
export const COURSE_CREATE_REVIEW_RESET = 'COURSE_CREATE_REVIEW_RESET'


